# Generated by Django 4.1.5 on 2023-03-10 05:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hallrecords.customFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventManager', models.CharField(max_length=100)),
                ('eventName', models.CharField(max_length=255)),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('organizingClub', models.CharField(blank=True, max_length=255)),
                ('EventDetailFile', models.FileField(max_length=250, null=True, upload_to='eventFile/')),
                ('EventDetailText', models.CharField(default='Details', max_length=5000)),
                ('PhoneNumber', hallrecords.customFields.NPPhoneNumberField(max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('put_in_queue', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='hallFile/')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('verified', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('bookedHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.hall')),
                ('booker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.event')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rejected_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='bookedHall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.hall'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('verified', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('bookedHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.hall')),
                ('booker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_events', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.event')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
