# Generated by Django 4.1.7 on 2023-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedHall', models.CharField(max_length=50)),
                ('eventName', models.CharField(max_length=255)),
                ('hallBooker', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventManager', models.CharField(max_length=255)),
                ('eventName', models.CharField(max_length=255)),
                ('eventDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
