# Generated by Django 4.1.5 on 2023-02-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventManager',
            field=models.CharField(max_length=100),
        ),
    ]
