# Generated by Django 4.1.5 on 2023-02-28 13:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0002_alter_event_eventmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventDetailFile',
            field=models.FileField(max_length=250, null=True, upload_to='eventFile/'),
        ),
        migrations.AddField(
            model_name='event',
            name='EventDetailText',
            field=models.CharField(default='Details', max_length=5000),
        ),
        migrations.AddField(
            model_name='event',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizingClub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
