# Generated by Django 4.1.5 on 2023-03-06 05:43

from django.db import migrations
import hallrecords.customFields


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0003_event_eventdetailfile_event_eventdetailtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='PhoneNumber',
            field=hallrecords.customFields.NPPhoneNumberField(max_length=20),
        ),
    ]
