# Generated by Django 4.1.5 on 2023-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0006_booking_eventdate_event_email_alter_booking_booker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
