# Generated by Django 4.1.5 on 2023-03-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0006_booking_eventdate_alter_booking_booker'),
        ('hallrecords', '0007_alter_event_email'),
    ]

    operations = [
    ]
