# Generated by Django 4.1.5 on 2023-03-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0008_merge_20230308_0844'),
        ('hallrecords', '0009_booking_rejected_alter_booking_eventdate'),
    ]

    operations = [
    ]
