# Generated by Django 4.1.5 on 2023-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0009_booking_rejected_alter_booking_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(null=True, upload_to='hallFile/'),
        ),
    ]
