# Generated by Django 4.1.5 on 2023-03-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0010_hall_image'),
        ('hallrecords', '0010_merge_20230308_1614'),
    ]

    operations = [
    ]
