# Generated by Django 4.1.5 on 2023-03-09 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hallrecords', '0010_hall_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('verified', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('bookedHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.hall')),
                ('booker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallrecords.event')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rejected_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
