# Generated by Django 4.1.5 on 2023-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0011_rejectedbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='put_in_queue',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
