# Generated by Django 4.1.5 on 2023-03-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallrecords', '0011_merge_0010_hall_image_0010_merge_20230308_1614'),
        ('hallrecords', '0012_event_put_in_queue'),
    ]

    operations = [
    ]
